name: Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    name: ğŸš€ Release
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checkout to the repository
        uses: actions/checkout@v3
      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache-dependency-path: package-lock.json
      - name: ğŸ“¦ Install packages
        run: pnpm install
      - name: ğŸ§± Build the app
        run: pnpm run build
      - name: ğŸš€ Package publish
        run: pnpm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ğŸ“Š Generate coverage reports
        run: npm run coverage
      - name: ğŸš€ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
